# API specific configurations
api_config:
  # 临时注释掉这些API用于测试
  # openai:
  #   base_url: "https://api.openai.com/v1"
  #   model: "gpt-4"
  #   api_key_env: "OPENAI_API_KEY"
  # anthropic:
  #   base_url: "https://api.anthropic.com/v1"
  #   model: "claude-3-5-sonnet-20241022"
  #   api_key_env: "ANTHROPIC_API_KEY"
  # gemini:
  #   base_url: "https://generativelanguage.googleapis.com/v1beta"
  #   model: "gemini-2.0-flash"
  #   api_key_env: "GEMINI_API_KEY"
  moonshot:
    base_url: "https://api.moonshot.cn/v1"
    model: "moonshot-v1-8k"
    api_key_env: "MOONSHOT_API_KEY"
  deepseek:
    base_url: "https://api.deepseek.com/v1"
    model: "deepseek-chat"
    api_key_env: "DEEPSEEK_API_KEY"

# 路径配置
paths:
  system_prompt: "prompt/system_prompt.txt"
  input_data: "test_set"
  output_results: "results"

# 评估配置
evaluation:
  batch_size: 10
  max_samples: 100  # 限制评估样本数量
  timeout: 30  # API调用超时时间（秒）
  
# 评估指标
metrics:
  - accuracy
  - relevance
  - completeness
  - consistency
